# -*- coding: utf-8 -*-
"""
JanusX: FASTQ -> VCF Pipeline Command-Line Interface

This CLI prepares metadata from a FASTQ directory and runs:
  fastp -> bwa-mem -> markdup -> gVCF -> joint-calling -> SNP filtering -> TSV

Requirements
------------
- Paired-end FASTQ files named as: *.R1.fastq.gz / *.R2.fastq.gz
- Reference FASTA with a .fai index (auto-generated by this CLI)

Examples
--------
  jx fastq2vcf \\
    --reference /data/ref.fa \\
    --fastq-dir /data/fastq \\
    --workdir /data/out \\
    --backend nohup \\
    --maxtask 2
"""

import os
import re
import time
import socket
import argparse
import sys
import subprocess
import shutil
import shlex
import urllib.request
from pathlib import Path
from collections import defaultdict
from typing import List, Optional, Sequence

import janusx.pipeline
from janusx.pipeline.fastq2vcf import fastq2vcf, indexREF
from janusx.pipeline.pipeline import wrap_cmd
from ._common.log import setup_logging
from ._common.config_render import emit_cli_configuration
from ._common.pathcheck import ensure_dir_exists, ensure_file_exists
from ._common.status import (
    CliStatus,
    get_rich_spinner_name,
    print_success,
    print_failure,
    format_elapsed,
)

try:
    from rich.progress import (
        Progress,
        SpinnerColumn,
        TextColumn,
        BarColumn,
        DownloadColumn,
        TransferSpeedColumn,
        TimeElapsedColumn,
    )
    _HAS_RICH_PROGRESS = True
except Exception:
    Progress = None  # type: ignore[assignment]
    SpinnerColumn = None  # type: ignore[assignment]
    TextColumn = None  # type: ignore[assignment]
    BarColumn = None  # type: ignore[assignment]
    DownloadColumn = None  # type: ignore[assignment]
    TransferSpeedColumn = None  # type: ignore[assignment]
    TimeElapsedColumn = None  # type: ignore[assignment]
    _HAS_RICH_PROGRESS = False

try:
    from tqdm.auto import tqdm
    _HAS_TQDM = True
except Exception:
    tqdm = None  # type: ignore[assignment]
    _HAS_TQDM = False

READ_RE = re.compile(r"\.(R[12])\.(fastq|fq)(\.gz)?$", re.IGNORECASE)
FASTQ_SUFFIXES = (".fastq", ".fq", ".fastq.gz", ".fq.gz")
REQUIRED_LOCAL_TOOLS = (
    "fastp",
    "bwa",
    "samtools",
    "gatk",
    "bcftools",
    "plink",
    "beagle",
)
DOCKER_IMAGE_TAG = "janusx-fastq2vcf:latest"


def _missing_binaries(commands: Sequence[str]) -> List[str]:
    return [cmd for cmd in commands if shutil.which(cmd) is None]


def _dockerfile_path() -> Path:
    pipeline_dir = Path(janusx.pipeline.__file__).resolve().parent
    return pipeline_dir / "docker" / "dockerfile"


def _collect_docker_mounts(reference: Path, fastq_dir: Path, workdir: Path) -> List[Path]:
    mounts: List[Path] = []
    seen: set[str] = set()
    for p in (reference.parent, fastq_dir, workdir):
        rp = Path(p).expanduser().resolve()
        key = str(rp)
        if key in seen:
            continue
        seen.add(key)
        mounts.append(rp)
    return mounts


def _docker_exec_prefix(image_tag: str, workdir: Path, mounts: Sequence[Path]) -> str:
    parts: List[str] = ["docker", "run", "--rm"]
    try:
        uid = int(os.getuid())
        gid = int(os.getgid())
        parts.extend(["--user", f"{uid}:{gid}"])
    except Exception:
        pass

    for mount in mounts:
        m = str(Path(mount).expanduser().resolve())
        parts.extend(["-v", f"{m}:{m}"])

    parts.extend(["-w", str(workdir), image_tag])
    return " ".join(shlex.quote(x) for x in parts)


def _build_docker_image(dockerfile: Path, image_tag: str, use_spinner: bool, logger) -> None:
    cmd = [
        "docker",
        "build",
        "-f",
        str(dockerfile),
        "-t",
        image_tag,
        str(dockerfile.parent),
    ]
    logger.info("Docker build: %s", " ".join(shlex.quote(x) for x in cmd))
    with CliStatus("Building Docker image...", enabled=use_spinner) as task:
        try:
            subprocess.run(cmd, check=True)
        except Exception:
            task.fail("Docker image build ...Failed")
            raise
        task.complete("Docker image build ...Finished")


def _docker_daemon_running(docker_bin: str) -> tuple[bool, str]:
    cmd = [str(docker_bin), "info"]
    try:
        p = subprocess.run(
            cmd,
            stdout=subprocess.DEVNULL,
            stderr=subprocess.PIPE,
            text=True,
            check=False,
        )
    except Exception as e:
        return False, str(e)
    if p.returncode == 0:
        return True, ""
    err = (p.stderr or "").strip()
    return False, err if err else "docker daemon unavailable"


class _DownloadProgress:
    """
    Download progress adapter: rich first, tqdm fallback.
    """
    def __init__(self, total: Optional[int], desc: str = "Downloading") -> None:
        self.total = total
        self.desc = desc
        self._backend = "none"
        self._progress = None
        self._task_id = None
        self._tqdm = None
        self._start_ts = time.monotonic()

        if _HAS_RICH_PROGRESS and sys.stdout.isatty():
            try:
                self._progress = Progress(
                    SpinnerColumn(
                        spinner_name=get_rich_spinner_name(),
                        style="cyan",
                        finished_text="[green]✔︎[/green]",
                    ),
                    TextColumn("[green]{task.description}"),
                    BarColumn(),
                    TextColumn("{task.percentage:>6.1f}%"),
                    DownloadColumn(),
                    TransferSpeedColumn(),
                    TimeElapsedColumn(),
                    transient=True,
                )
                self._progress.start()
                self._task_id = self._progress.add_task(
                    self.desc,
                    total=self.total,
                )
                self._backend = "rich"
            except Exception:
                self._progress = None
                self._task_id = None

        if self._backend == "none" and _HAS_TQDM:
            self._tqdm = tqdm(
                total=self.total,
                desc=self.desc,
                unit="B",
                unit_scale=True,
                unit_divisor=1024,
                leave=False,
                bar_format="{desc}: {percentage:3.0f}%|{bar}| "
                           "[{elapsed}, {rate_fmt}{postfix}]",
            )
            self._backend = "tqdm"

    def update(self, n_bytes: int) -> None:
        step = int(max(0, n_bytes))
        if step == 0:
            return
        if self._backend == "rich" and self._progress is not None and self._task_id is not None:
            self._progress.update(self._task_id, advance=step)
        elif self._backend == "tqdm" and self._tqdm is not None:
            self._tqdm.update(step)

    def close(self, *, success: bool = True) -> None:
        elapsed_text = format_elapsed(time.monotonic() - self._start_ts)
        if self._backend == "rich" and self._progress is not None:
            if success and self._task_id is not None and self.total is not None:
                try:
                    self._progress.update(self._task_id, completed=int(self.total))
                except Exception:
                    pass
            self._progress.stop()
            self._progress = None
            self._task_id = None
        elif self._backend == "tqdm" and self._tqdm is not None:
            self._tqdm.close()
            self._tqdm = None
        if success:
            print_success(f"{self.desc} ...Finished [{elapsed_text}]")
        else:
            print_failure(f"{self.desc} ...Failed [{elapsed_text}]")


def downloader(url: str, dst: Path) -> None:
    dst = Path(dst)
    dst.parent.mkdir(parents=True, exist_ok=True)
    tmp = dst.with_suffix(dst.suffix + ".tmp")

    with urllib.request.urlopen(url) as r, open(tmp, "wb") as f:
        total = r.headers.get("Content-Length")
        total = int(total) if total is not None else None
        pbar = _DownloadProgress(total=total, desc="Downloading JanusX image")
        ok = False
        try:
            while True:
                chunk = r.read(1024 * 1024)
                if not chunk:
                    break
                f.write(chunk)
                pbar.update(len(chunk))
            ok = True
        finally:
            pbar.close(success=ok)

    os.replace(tmp, dst)


def _fastq_read_info(name: str):
    m = READ_RE.search(name)
    if not m:
        return None
    read = m.group(1).upper()
    stem = name[:m.start()]
    parts = stem.split("_")
    sample = parts[0]
    lane = parts[1] if len(parts) > 1 else None
    return sample, lane, read


def two_level_cluster(fastqlist):
    level1 = defaultdict(list)
    meta = {}

    for f in fastqlist:
        f = Path(f)
        if not f.name.lower().endswith(FASTQ_SUFFIXES):
            continue
        info = _fastq_read_info(f.name)
        if not info:
            continue
        sample, lane, read = info
        level1[sample].append(f)
        meta[f] = (sample, lane, read)

    level2 = {}
    for sample, files in level1.items():
        if len(files) == 4:
            sub = defaultdict(list)
            for f in files:
                s, lane, _ = meta[f]
                sub[(s, lane)].append(f)
            level2[sample] = dict(sub)

    return dict(level1), level2


def _pair_fastqs(files, sample_hint: str) -> tuple[Path, Path]:
    r1 = None
    r2 = None
    for f in sorted(files):
        info = _fastq_read_info(f.name)
        if not info:
            continue
        read = info[2]
        if read == "R1":
            if r1 is not None:
                raise ValueError(f"Duplicate R1 for sample {sample_hint}: {f}")
            r1 = f
        elif read == "R2":
            if r2 is not None:
                raise ValueError(f"Duplicate R2 for sample {sample_hint}: {f}")
            r2 = f

    if r1 is None or r2 is None:
        raise ValueError(f"Missing R1/R2 for sample {sample_hint}: {files}")
    return r1, r2


def build_samples(level1, level2):
    samples = {}
    for sample, files in level1.items():
        if len(files) == 2:
            r1, r2 = _pair_fastqs(files, sample)
            samples[sample] = [r1, r2]
            continue

        if len(files) == 4 and sample in level2:
            for (s, lane), lane_files in level2[sample].items():
                r1, r2 = _pair_fastqs(lane_files, f"{s}_{lane}")
                key = f"{s}_{lane}" if lane else s
                samples[key] = [r1, r2]
            continue

        raise ValueError(
            f"Sample {sample} has {len(files)} FASTQ files. "
            "Expected 2 (R1/R2) or 4 (two lanes) files."
        )
    return samples


def _infer_bulks(samples: Sequence[str]) -> List[str]:
    """
    Infer bulk names from sample keys.
    Heuristic: use token before first "_" when it yields >=2 groups.
    """
    sample_keys = sorted({str(s) for s in samples if str(s).strip()})
    if len(sample_keys) == 0:
        return []
    prefix_keys = [s.split("_", 1)[0] if "_" in s else s for s in sample_keys]
    prefix_unique = sorted(set(prefix_keys))
    if len(prefix_unique) >= 2:
        return prefix_unique
    return sample_keys


def _latest_snp_table(workdir: Path) -> Optional[Path]:
    merge_dir = workdir / "4.merge"
    if not merge_dir.exists():
        return None
    tables = [p for p in merge_dir.glob("Merge.*.SNP.tsv") if p.is_file()]
    if len(tables) == 0:
        return None
    try:
        return max(tables, key=lambda p: p.stat().st_mtime)
    except Exception:
        return sorted(tables)[-1]


def read_chroms_from_fai(reference: Path) -> List[str]:
    fai = Path(f"{reference}.fai")
    if not fai.exists():
        raise FileNotFoundError(f"FASTA index not found: {fai}")
    chroms: List[str] = []
    with open(fai, "r", encoding="utf-8") as f:
        for line in f:
            if not line.strip():
                continue
            chrom = line.split("\t", 1)[0].strip()
            if chrom:
                chroms.append(chrom)
    if not chroms:
        raise ValueError(f"Empty FASTA index: {fai}")
    return chroms


def main():
    t_start = time.time()
    use_spinner = bool(getattr(sys.stdout, "isatty", lambda: False)())

    parser = argparse.ArgumentParser(
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__,
    )

    required_group = parser.add_argument_group("Required Arguments")
    required_group.add_argument(
        "-r", "--reference", required=True, type=str,
        help="Reference genome FASTA file.",
    )
    required_group.add_argument(
        "-i", "--fastq-dir", required=True, type=str,
        help="Directory containing FASTQ files.",
    )
    required_group.add_argument(
        "-w", "--workdir", required=True, type=str,
        help="Working directory for outputs.",
    )
    optional_group = parser.add_argument_group("Optional Arguments")
    optional_group.add_argument(
        "-b", "--backend", required=False, type=str,default='nohup',
        choices=["nohup", "csub"],
        help=f"Execution backend for the pipeline. (default: nohup)",
    )
    optional_group.add_argument(
        "-m", "--maxtask", required=False, type=int,default=1,
        help="Max concurrent jobs when backend=nohup. (default: 1)",
    )

    args = parser.parse_args()

    workdir = Path(args.workdir).expanduser().resolve()
    workdir.mkdir(parents=True, exist_ok=True)
    (workdir / "log").mkdir(parents=True, exist_ok=True)
    (workdir / "tmp").mkdir(parents=True, exist_ok=True)
    log_path = workdir / "fastq2vcf.log"
    logger = setup_logging(str(log_path))

    reference = Path(args.reference).expanduser().resolve()
    if not ensure_file_exists(logger, str(reference), "Reference file"):
        raise SystemExit(1)

    fastq_dir = Path(args.fastq_dir).expanduser().resolve()
    if not ensure_dir_exists(logger, str(fastq_dir), "FASTQ directory"):
        raise SystemExit(1)

    emit_cli_configuration(
        logger,
        app_title="JanusX - Fastq2VCF",
        config_title="FASTQ2VCF CONFIG",
        host=socket.gethostname(),
        sections=[
            (
                "General",
                [
                    ("Reference", reference),
                    ("FASTQ dir", fastq_dir),
                    ("Workdir", workdir),
                    ("Backend", args.backend),
                    ("Max tasks (nohup)", args.maxtask),
                ],
            )
        ],
        line_max_chars=60,
    )

    exec_prefix = ""
    runtime_mode = "local"
    missing_tools = _missing_binaries(REQUIRED_LOCAL_TOOLS)
    if len(missing_tools) == 0:
        logger.info(
            "Using local runtime. Found dependencies: %s",
            ", ".join(REQUIRED_LOCAL_TOOLS),
        )
    else:
        logger.warning("Missing local dependencies: %s", ", ".join(missing_tools))
        docker_bin = shutil.which("docker")
        docker_ready = False
        docker_err = ""
        if docker_bin is not None:
            docker_ready, docker_err = _docker_daemon_running(docker_bin)

        if docker_bin is not None and docker_ready:
            dockerfile = _dockerfile_path()
            if not dockerfile.exists():
                logger.error(f"Dockerfile not found: {dockerfile}")
                raise SystemExit(1)
            _build_docker_image(
                dockerfile=dockerfile,
                image_tag=DOCKER_IMAGE_TAG,
                use_spinner=use_spinner,
                logger=logger,
            )
            docker_mounts = _collect_docker_mounts(
                reference=reference,
                fastq_dir=fastq_dir,
                workdir=workdir,
            )
            exec_prefix = _docker_exec_prefix(
                image_tag=DOCKER_IMAGE_TAG,
                workdir=workdir,
                mounts=docker_mounts,
            )
            runtime_mode = "docker"
            logger.info("Docker runtime enabled.")
            logger.info("Docker prefix: %s", exec_prefix)
        else:
            if docker_bin is not None and not docker_ready:
                logger.warning(
                    "Docker command found but daemon is not running. "
                    "Falling back to singularity. detail: %s",
                    docker_err,
                )
            singularity_bin = shutil.which("singularity")
            if singularity_bin is None:
                logger.error(
                    "Missing local dependencies (%s), and no usable container runtime is available.",
                    ", ".join(missing_tools)
                )
                raise SystemExit(1)

            binary_path = Path(janusx.pipeline.__file__).resolve().parent / "bin"
            binary_path.mkdir(parents=True, exist_ok=True)
            sif_path = binary_path / "janusxext.sif"
            if not sif_path.exists():
                user_input = input(
                    "Download JanusX Singularity Image (~800MB)? [y/N or /path/to.sif]: "
                ).strip()
                if not user_input or user_input.lower() == "n":
                    raise SystemExit(1)
                tmp_path = binary_path / "janusxext.tmp.sif"
                if user_input.lower() == "y":
                    downloader(
                        "https://github.com/FJingxian/JanusX/releases/download/v1.0.10/janusxext.sif",
                        tmp_path,
                    )
                else:
                    src = Path(user_input).expanduser().resolve()
                    if not src.exists():
                        logger.error(f"SIF path not found: {src}")
                        raise SystemExit(1)
                    shutil.copy2(src, tmp_path)

                # subprocess.run([str(tmp_path), "gatk", "-version"], shell=True, check=True)
                os.replace(tmp_path, sif_path)
                logger.info(f"Saved in {sif_path}")

            exec_prefix = (
                f"{shlex.quote(str(singularity_bin))} exec "
                f"{shlex.quote(str(sif_path))}"
            )
            runtime_mode = "singularity"
            logger.info("Singularity runtime enabled.")
            logger.info("Singularity prefix: %s", exec_prefix)

    logger.info("Execution runtime: %s", runtime_mode)

    fai_path = Path(f"{reference}.fai")
    ann_path = Path(f"{reference}.ann")
    if not fai_path.exists() or not ann_path.exists():
        cmd = indexREF(str(reference), singularity=exec_prefix)
        logger.info(f"Indexing reference: {cmd}")
        index_job = wrap_cmd(cmd, "indexREF", 1, scheduler=args.backend)
        with CliStatus("Indexing reference...", enabled=use_spinner) as task:
            try:
                subprocess.run(index_job, shell=True, check=True, cwd=workdir)
            except Exception:
                task.fail("Reference indexing ...Failed")
                raise
            task.complete("Reference indexing started")
        with CliStatus("Waiting for FASTA index files...", enabled=use_spinner) as task:
            while (not fai_path.exists()) or (not ann_path.exists()):
                time.sleep(5)
            task.complete("Reference index files ready")

    chrom = read_chroms_from_fai(reference)
    logger.info(f"Chromosomes: {len(chrom)}")

    fastqlist = sorted(
        p for p in fastq_dir.rglob("*")
        if p.is_file() and p.name.lower().endswith(FASTQ_SUFFIXES)
    )
    if not fastqlist:
        logger.error(f"No FASTQ files found in {fastq_dir}")
        raise SystemExit(1)

    level1, level2 = two_level_cluster(fastqlist)
    samples = build_samples(level1, level2)
    logger.info(f"Samples: {len(samples)}")

    metadata = {
        "reference": str(reference),
        "samples": {k: [str(v[0]), str(v[1])] for k, v in samples.items()},
        "chrom": chrom,
    }

    os.chdir(workdir)
    fastq2vcf(
        metadata=metadata,
        workdir=workdir,
        backbend=args.backend,
        nohup_max_jobs=args.maxtask,
        singularity=exec_prefix,
    )

    bulks = _infer_bulks(list(samples.keys()))
    latest_tsv = _latest_snp_table(workdir)
    if latest_tsv is not None:
        tsv_token = str(latest_tsv)
    elif len(chrom) > 0:
        tsv_token = str(workdir / "4.merge" / f"Merge.{chrom[-1]}.SNP.tsv")
    else:
        tsv_token = str(workdir / "4.merge" / "Merge.<chrom>.SNP.tsv")

    logger.info("")
    logger.info("Detected bulks: %s", ", ".join(bulks) if len(bulks) > 0 else "None")
    logger.info("Latest SNP table: %s", tsv_token)
    logger.info("Next step suggestion:")
    logger.info("  jx postbsa -file %s -b1 [bulk1] -b2 [bulk2]", tsv_token)
    if len(bulks) >= 2:
        logger.info(
            "  Example: jx postbsa -file %s -b1 %s -b2 %s",
            tsv_token,
            bulks[0],
            bulks[1],
        )

    lt = time.localtime()
    endinfo = (
        f"\nFinished. Total wall time: {round(time.time() - t_start, 2)} seconds\n"
        f"{lt.tm_year}-{lt.tm_mon}-{lt.tm_mday} "
        f"{lt.tm_hour}:{lt.tm_min}:{lt.tm_sec}"
    )
    logger.info(endinfo)


if __name__ == "__main__":
    main()
