"""
Backward-compatible re-export shim for JanusX shared CLI helpers.
"""

from __future__ import annotations

from .cli_args import (
    add_common_covariate_file_arg,
    add_common_covariate_file_or_site_arg,
    add_common_geno_arg,
    add_common_genotype_source_args,
    add_common_grm_file_arg,
    add_common_grm_option_arg,
    add_common_het_arg,
    add_common_maf_arg,
    add_common_memory_arg,
    add_common_out_arg,
    add_common_pheno_arg,
    add_common_prefix_arg,
    add_common_snps_only_arg,
    add_common_thread_arg,
    add_common_trait_selector_args,
    add_common_variant_filter_args,
    covariate_file_help_text,
    covariate_file_or_site_help_text,
    grm_option_help_text,
    het_filter_help_text,
    maf_filter_help_text,
    missing_rate_filter_help_text,
    parse_trait_selector_specs,
    resolve_trait_selectors,
    snps_only_help_text,
    trait_selector_help_text,
)
from .cli_core import CliArgumentParser, cli_help_formatter, minimal_help_epilog

__all__ = [
    "CliArgumentParser",
    "add_common_covariate_file_arg",
    "add_common_covariate_file_or_site_arg",
    "add_common_geno_arg",
    "add_common_genotype_source_args",
    "add_common_grm_file_arg",
    "add_common_grm_option_arg",
    "add_common_het_arg",
    "add_common_maf_arg",
    "add_common_memory_arg",
    "add_common_out_arg",
    "add_common_pheno_arg",
    "add_common_prefix_arg",
    "add_common_snps_only_arg",
    "add_common_thread_arg",
    "add_common_trait_selector_args",
    "add_common_variant_filter_args",
    "cli_help_formatter",
    "covariate_file_help_text",
    "covariate_file_or_site_help_text",
    "grm_option_help_text",
    "het_filter_help_text",
    "maf_filter_help_text",
    "minimal_help_epilog",
    "missing_rate_filter_help_text",
    "parse_trait_selector_specs",
    "resolve_trait_selectors",
    "snps_only_help_text",
    "trait_selector_help_text",
]
