{% set name = "janusx" %}
{% set version = "1.0.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  path: ../..

build:
  number: 0
  skip: true  # [win or py<39 or py>312]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('rust') }}
  host:
    - python
    - pip
    - maturin >=1.7,<2
    - numpy
  run:
    - python
    - numpy
    - pandas <3.0
    - scipy
    - matplotlib
    - psutil
    - tqdm
    - scikit-learn ==1.8.0
    - joblib >=1.5.2

test:
  imports:
    - JanusX
  commands:
    - jx -h

about:
  home: https://github.com/MaizeMan-JxFU/JanusX
  license: MIT
  license_file: LICENSE
  summary: High-performance GWAS and genomic selection suite
