FROM ubuntu:22.04

ARG DEBIAN_FRONTEND=noninteractive
ARG GATK_VER="4.6.2.0"
ARG BEAGLE_JAR_URL="https://faculty.washington.edu/browning/beagle/beagle.28Jun21.220.jar"
ARG PLINK19_URL="https://s3.amazonaws.com/plink1-assets/plink_linux_x86_64_20231211.zip"

RUN apt-get update && apt-get install -y --no-install-recommends \
    ca-certificates curl wget unzip git \
    tabix bcftools \
    bash gawk coreutils sed grep findutils \
    python3 python3-pip python3-venv \
    openjdk-17-jre-headless \
    bwa samtools sambamba fastp \
    libgomp1 \
 && ln -sf /usr/bin/python3 /usr/local/bin/python \
 && rm -rf /var/lib/apt/lists/*

RUN python3 -m pip install --no-cache-dir -U pip setuptools wheel

WORKDIR /opt

RUN mkdir -p /opt/gatk \
    && wget -O /opt/gatk/gatk-${GATK_VER}.zip \
        https://github.com/broadinstitute/gatk/releases/download/${GATK_VER}/gatk-${GATK_VER}.zip \
    && unzip /opt/gatk/gatk-${GATK_VER}.zip -d /opt/gatk \
    && rm -f /opt/gatk/gatk-${GATK_VER}.zip

RUN mkdir -p /opt/beagle \
    && wget -O /opt/beagle/beagle.jar "${BEAGLE_JAR_URL}" \
    && printf '%s\n' '#!/usr/bin/env bash' \
       'exec java -jar /opt/beagle/beagle.jar "$@"' \
       > /usr/local/bin/beagle \
    && chmod +x /usr/local/bin/beagle

RUN mkdir -p /opt/plink \
    && wget -O /opt/plink/plink.zip "${PLINK19_URL}" \
    && unzip /opt/plink/plink.zip -d /opt/plink \
    && rm -f /opt/plink/plink.zip \
    && if [ -x /opt/plink/plink ]; then ln -sf /opt/plink/plink /usr/local/bin/plink; fi \
    && if [ -x /opt/plink/plink1.9 ]; then ln -sf /opt/plink/plink1.9 /usr/local/bin/plink; fi

ENV PATH="/opt/gatk/gatk-${GATK_VER}:$PATH" \
    GATK_LOCAL_JAR="/opt/gatk/gatk-${GATK_VER}/gatk-package-${GATK_VER}-local.jar" \
    MALLOC_ARENA_MAX=2 \
    JAVA_TOOL_OPTIONS="-Djava.io.tmpdir=/tmp"

RUN command -v fastp \
    && command -v bwa \
    && command -v samtools \
    && command -v sambamba \
    && command -v gatk \
    && command -v bcftools \
    && command -v tabix \
    && command -v plink \
    && command -v beagle \
    && command -v awk \
    && command -v sort

WORKDIR /work

CMD ["/bin/bash"]
